l = []
a1 = input("Enter the fruits:")
l.append(a1)
a2 = input("Enter the fruits:")
l.append(a2)
a3 = input("Enter the fruits:")
l.append(a3)
a4 = input("Enter the fruits:")
l.append(a4)
a5 = input("Enter the fruits:")
l.append(a5)
a6 = input("Enter the fruits:")
l.append(a6)
print("name of fruits: ",l)