marks = []
a1 = int(input("Enter the mark:"))
marks.append(a1)
a2 = int(input("Enter the mark:"))
marks.append(a2)
a3 = int(input("Enter the mark:"))
marks.append(a3)
a4 = int(input("Enter the mark:"))
marks.append(a4)
a5 = int(input("Enter the mark:"))
marks.append(a5)
a6 = int(input("Enter the mark:"))
marks.append(a6)
marks.sort()
print("marks: ",marks)